// GENERATED by build_case.py from the routed board. Edit build_case.py, not this file.
// Bottom tray. World frame: ergogen xy, z = 0 under the floor. Flat floor; the PCB sits on the
// pillars + corner ledges parallel to the sloped top edge; the switch plate drops in flush with the top.

var TILT = 2.37, Y_PIVOT = 6.575, Z_REAR = 8.1;
// board frame -> world: tilt about x around the PCB rear edge, then lift
function T(o) { return o.translate([0, -Y_PIVOT, 0]).rotateX(TILT).translate([0, Y_PIVOT, Z_REAR]); }
function rrect(c, r, rr) { return CAG.roundedRectangle({ center: c, radius: r, roundradius: rr, resolution: 32 }); }

function main() {
    var floorT = 1.0, plateTop = 3.8000000000000003, gap = 0.4;
    var cx = 128.5, cy = -52.5, OUT = [82.9, 120.9, 3.45], INN = [80.5, 118.5, 2.25];
    var yRearIn = 6.75, yRear = 7.950000000000003;
    var posts = [[109.5, -90.5], [109.5, -33.5], [128.5, -52.5], [147.5, -90.5], [147.5, -14.5]], postR = 3.0, screwR = 1.1, ledges = [[87.25, -112.75, 98.25, -110.15], [87.25, -112.75, 89.85, -101.75], [87.25, 5.15, 98.25, 7.75], [87.25, -3.25, 89.85, 7.75], [158.75, -112.75, 169.75, -110.15], [167.15, -112.75, 169.75, -101.75], [158.75, 5.15, 169.75, 7.75], [167.15, -3.25, 169.75, 7.75]];
    var cuts = {"usb": [121.567, 4.07, 8.94, 3.26], "rst": [137.2, 0.85, 2.6, 1.0], "pwr": [148.5, 0.7, 3.3, 0.8]};   // [x, depth-centre below PCB, w, h] in board frame
    var outer = rrect([cx, cy], [OUT[0] / 2, OUT[1] / 2], OUT[2]);
    var inner = rrect([cx, cy], [INN[0] / 2, INN[1] / 2], INN[2]);
    var tray = outer.extrude({ offset: [0, 0, 40] })
        .subtract(inner.extrude({ offset: [0, 0, 50] }).translate([0, 0, floorT]));
    // anything above the plate top plane goes (walls end flush with the plate)
    var big = 400;
    var abovePlate = T(CSG.cube({ corner1: [cx - big, cy - big, plateTop], corner2: [cx + big, cy + big, plateTop + big] }));
    var belowPcb   = T(CSG.cube({ corner1: [cx - big, cy - big, -big], corner2: [cx + big, cy + big, 0] }));
    tray = tray.subtract(abovePlate);

    // supports: screw pillars + corner ledges, trimmed to the (tilted) PCB underside
    var sup = null;
    for (var i = 0; i < posts.length; i++) {
        var c = CSG.cylinder({ start: [posts[i][0], posts[i][1], 0], end: [posts[i][0], posts[i][1], 30], radius: postR, resolution: 32 });
        sup = sup ? sup.union(c) : c;
    }
    for (var k = 0; k < ledges.length; k++) {
        var L = ledges[k];
        sup = sup.union(CSG.cube({ corner1: [L[0], L[1], 0], corner2: [L[2], L[3], 30] }));
    }
    tray = tray.union(sup.intersect(belowPcb));
    for (var j = 0; j < posts.length; j++) {
        tray = tray.subtract(CSG.cylinder({ start: [posts[j][0], posts[j][1], -1], end: [posts[j][0], posts[j][1], 40], radius: screwR, resolution: 32 }));
    }

    // rear-wall windows: part outline + gap, in the board frame, then tilted with the board
    function wallSlab(prof, y0, y1) {   // profile drawn in (x, z) -> slab spanning y0..y1
        return prof.extrude({ offset: [0, 0, y1 - y0] }).rotateX(90).translate([0, y1, 0]);
    }
    function win(c, rr, extraW, extraH, y0, y1) {
        return T(wallSlab(rrect([c[0], -c[1]], [c[2] / 2 + extraW, c[3] / 2 + extraH], rr), y0, y1));
    }
    tray = tray.subtract(win(cuts.usb, 1.2, gap, gap, yRearIn - 1, yRear + 1));
    // outer pocket so a USB-C plug overmold (~12 x 6.5) gets close enough to seat
    tray = tray.subtract(T(wallSlab(rrect([cuts.usb[0], -cuts.usb[1]], [6.4, 3.4], 2.0), yRear - 0.6, yRear + 1)));
    tray = tray.subtract(win(cuts.rst, 0.6, gap, gap, yRearIn - 1, yRear + 1));
    tray = tray.subtract(win(cuts.pwr, 0.6, gap, gap, yRearIn - 1, yRear + 1));
    // nail scoop around the power lever
    tray = tray.subtract(T(wallSlab(rrect([cuts.pwr[0], -cuts.pwr[1]], [3.2, 1.9], 1.2), yRear - 0.5, yRear + 1)));
    return tray;
}
