// GENERATED by build_case.py from the routed board. Edit build_case.py, not this file.
// Switch plate, flat in the board frame (print orientation): z = 0 at the PCB underside, so the
// plate spans z 2.6000000000000005..3.8000000000000003. It drops inside the tray walls (0.2mm clearance per side).

var TILT = 2.37, Y_PIVOT = 6.575, Z_REAR = 8.1;
// board frame -> world: tilt about x around the PCB rear edge, then lift
function T(o) { return o.translate([0, -Y_PIVOT, 0]).rotateX(TILT).translate([0, Y_PIVOT, Z_REAR]); }
function rrect(c, r, rr) { return CAG.roundedRectangle({ center: c, radius: r, roundradius: rr, resolution: 32 }); }

function main() {
    var cx = 128.5, cy = -52.5, INN = [80.5, 118.5, 2.25], tol = 0.2;
    var sw = [[100.0, -24.0, 0.0], [157.0, -5.0, 0.0], [119.0, -81.0, 0.0], [138.0, -81.0, 0.0], [119.0, -5.0, 0.0], [109.5, -100.0, 0.0], [138.0, -100.0, 0.0], [100.0, -43.0, 0.0], [138.0, -24.0, 0.0], [157.0, -24.0, 0.0], [138.0, -43.0, 0.0], [138.0, -62.0, 0.0], [119.0, -24.0, 0.0], [119.0, -62.0, 0.0], [119.0, -43.0, 0.0], [138.0, -5.0, 0.0], [100.0, -81.0, 0.0], [157.0, -90.5, 0.0], [100.0, -5.0, 0.0], [100.0, -62.0, 0.0], [157.0, -52.5, 0.0]], swCut = 14.0, holes = [[109.5, -90.5], [109.5, -33.5], [128.5, -52.5], [147.5, -90.5], [147.5, -14.5]], screwR = 1.1, reliefs = [[127.81, -0.05, 130.31, 2.45], [127.81, -2.59, 130.31, -0.09], [127.81, -5.13, 130.31, -2.63], [127.81, -7.67, 130.31, -5.17], [127.81, -15.29, 130.31, -12.79], [127.81, -17.83, 130.31, -15.33], [127.81, -20.37, 130.31, -17.87], [127.81, -22.91, 130.31, -20.41], [127.81, -25.45, 130.31, -22.95], [112.57, -25.45, 115.07, -22.95], [112.57, -22.91, 115.07, -20.41], [112.57, -20.37, 115.07, -17.87], [112.57, -17.83, 115.07, -15.33], [112.57, -15.29, 115.07, -12.79], [112.57, -7.67, 115.07, -5.17], [112.57, -5.13, 115.07, -2.63], [112.57, -2.59, 115.07, -0.09], [112.57, -0.05, 115.07, 2.45], [136.425, 4.85, 137.975, 6.4], [136.425, 2.1, 137.975, 3.65], [127.225, -32.5, 129.775, -30.5], [127.225, -34.5, 129.775, -32.5], [146.15, 3.88, 147.85, 5.58], [149.15, 3.88, 150.85, 5.58]];
    var shape = rrect([cx, cy], [INN[0] / 2 - tol, INN[1] / 2 - tol], INN[2] - tol);
    for (var i = 0; i < sw.length; i++) {
        shape = shape.subtract(CAG.rectangle({ center: [0, 0], radius: [swCut / 2, swCut / 2] })
            .rotateZ(sw[i][2]).translate([sw[i][0], sw[i][1]]));
    }
    for (var j = 0; j < holes.length; j++) {
        shape = shape.subtract(CAG.circle({ center: holes[j], radius: screwR, resolution: 32 }));
    }
    for (var k = 0; k < reliefs.length; k++) {
        var r = reliefs[k];
        shape = shape.subtract(CAG.rectangle({ corner1: [r[0], r[1]], corner2: [r[2], r[3]] }));
    }
    return shape.extrude({ offset: [0, 0, 1.2] }).translate([0, 0, 2.6000000000000005]);
}
