// GENERATED by build_case.py from the board. Edit build_case.py, not this file.
// Bottom tray. World frame: ergogen xy, z = 0 under the floor. Flat floor; the PCB sits on the
// pillars + corner ledges parallel to the sloped top edge; the switch plate drops in flush with the top.

var TILT = 2.37, Y_PIVOT = 4.75, Z_REAR = 8.1;
// board frame -> world: tilt about x around the PCB rear edge, then lift
function T(o) { return o.translate([0, -Y_PIVOT, 0]).rotateX(TILT).translate([0, Y_PIVOT, Z_REAR]); }
function rrect(c, r, rr) { return CAG.roundedRectangle({ center: c, radius: r, roundradius: rr, resolution: 32 }); }

function main() {
    var floorT = 1.0, plateTop = 3.8000000000000003, gap = 0.4;
    var cx = 128.5, cy = -52.5, OUT = [79.4, 117.4, 1.7], INN = [77.0, 115.0, 0.5];
    var yRearIn = 5.0, yRear = 6.2;
    var posts = [[147.5, -14.5], [109.5, -33.5], [128.5, -90.5], [128.5, -52.5], [147.5, -71.5]], postR = 3.0, pilotR = 0.8, pilotD = [4.7, 4.7, 2.7, 4.7, 2.7], ledges = [[90.0, -110.0, 100.0, -108.4], [90.0, -110.0, 91.6, -100.0], [90.0, 3.4, 100.0, 5.0], [90.0, -5.0, 91.6, 5.0], [157.0, -110.0, 167.0, -108.4], [165.4, -110.0, 167.0, -100.0], [157.0, 3.4, 167.0, 5.0], [165.4, -5.0, 167.0, 5.0]];
    var cuts = {"rst": [137.2, 0.85, 2.6, 1.0], "pwr": [148.5, 0.65, 2.8, 1.1], "usb": [121.567, 4.07, 8.94, 3.26]};   // [x, depth-centre below PCB, w, h] in board frame
    var batt = [98.5, -27.5, 110.5, 2.5], wire = [102.5, -34.0, 106.5, -27.5], battD = 0.5, battGap = 0.5;
    var outer = rrect([cx, cy], [OUT[0] / 2, OUT[1] / 2], OUT[2]);
    var inner = rrect([cx, cy], [INN[0] / 2, INN[1] / 2], INN[2]);
    var cavity = inner.extrude({ offset: [0, 0, 50] });
    var tray = outer.extrude({ offset: [0, 0, 40] }).subtract(cavity.translate([0, 0, floorT]));
    // anything above the plate top plane goes (walls end flush with the plate)
    var big = 400;
    var abovePlate = T(CSG.cube({ corner1: [cx - big, cy - big, plateTop], corner2: [cx + big, cy + big, plateTop + big] }));
    var belowPcb   = T(CSG.cube({ corner1: [cx - big, cy - big, -big], corner2: [cx + big, cy + big, 0] }));
    tray = tray.subtract(abovePlate);

    // supports: screw pillars + corner ledges, trimmed to the (tilted) PCB underside and
    // kept inside the cavity so nothing pokes through the walls
    var sup = null;
    for (var i = 0; i < posts.length; i++) {
        var c = CSG.cylinder({ start: [posts[i][0], posts[i][1], 0], end: [posts[i][0], posts[i][1], 30], radius: postR, resolution: 32 });
        sup = sup ? sup.union(c) : c;
    }
    for (var k = 0; k < ledges.length; k++) {
        var L = ledges[k];
        sup = sup.union(CSG.cube({ corner1: [L[0], L[1], 0], corner2: [L[2], L[3], 30] }));
    }
    tray = tray.union(sup.intersect(belowPcb).intersect(cavity));
    for (var j = 0; j < posts.length; j++) {
        // blind pilot square to the tilted board (matches the screw axis); the floor stays closed
        tray = tray.subtract(T(CSG.cylinder({ start: [posts[j][0], posts[j][1], 1], end: [posts[j][0], posts[j][1], -pilotD[j]], radius: pilotR, resolution: 24 })));
    }

    // rear-wall windows: part outline + gap, in the board frame, then tilted with the board
    function wallSlab(prof, y0, y1) {   // profile drawn in (x, z) -> slab spanning y0..y1
        return prof.extrude({ offset: [0, 0, y1 - y0] }).rotateX(90).translate([0, y1, 0]);
    }
    function win(c, rr, y0, y1) {
        return T(wallSlab(rrect([c[0], -c[1]], [c[2] / 2 + gap, c[3] / 2 + gap], rr), y0, y1));
    }
    tray = tray.subtract(win(cuts.usb, 1.2, yRearIn - 1, yRear + 1));
    // outer pocket so a USB-C plug overmold (~12 x 6.5) gets close enough to seat
    tray = tray.subtract(T(wallSlab(rrect([cuts.usb[0], -cuts.usb[1]], [6.4, 3.4], 2.0), yRear - 0.6, yRear + 1)));
    tray = tray.subtract(win(cuts.rst, 0.6, yRearIn - 1, yRear + 1));
    tray = tray.subtract(win(cuts.pwr, 0.6, yRearIn - 1, yRear + 1));
    // nail scoop around the power lever
    tray = tray.subtract(T(wallSlab(rrect([cuts.pwr[0], -cuts.pwr[1]], [3.2, 1.9], 1.2), yRear - 0.5, yRear + 1)));
    // battery pocket in the floor (cell + gap), plus a notch for its lead toward the JST
    if (batt) {
        var bg = battGap;
        tray = tray.subtract(CSG.cube({ corner1: [batt[0] - bg, batt[1] - bg, floorT - battD], corner2: [batt[2] + bg, batt[3] + bg, floorT + 0.01] }));
        tray = tray.subtract(CSG.cube({ corner1: [wire[0], wire[1], floorT - battD], corner2: [wire[2], wire[3], floorT + 0.01] }));
    }
    return tray;
}
