// GENERATED by build_case.py from the board. Edit build_case.py, not this file.
// Switch plate in the board frame (z = 0 at the PCB underside): plate 2.6..3.8000000000000003, with a rim and
// spacer bosses underneath reaching down to the PCB top (z = 1.6). Pin reliefs are blind pockets
// from below; screw holes are countersunk from the top. Print it upside down.
// It drops inside the tray walls (0.2mm clearance per side).

var TILT = 2.37, Y_PIVOT = 4.75, Z_REAR = 8.1;
// board frame -> world: tilt about x around the PCB rear edge, then lift
function T(o) { return o.translate([0, -Y_PIVOT, 0]).rotateX(TILT).translate([0, Y_PIVOT, Z_REAR]); }
function rrect(c, r, rr) { return CAG.roundedRectangle({ center: c, radius: r, roundradius: rr, resolution: 32 }); }

function main() {
    var cx = 128.5, cy = -52.5, pw = 76.6, ph = 114.6, pr = 0.3;
    var sw = [[157.0, -90.5], [119.0, -5.0], [119.0, -24.0], [119.0, -62.0], [100.0, -5.0], [157.0, -5.0], [100.0, -62.0], [138.0, -62.0], [138.0, -5.0], [138.0, -100.0], [157.0, -24.0], [119.0, -81.0], [109.5, -100.0], [119.0, -43.0], [100.0, -43.0], [100.0, -81.0], [138.0, -43.0], [157.0, -52.5], [100.0, -24.0], [138.0, -81.0], [138.0, -24.0]], swCut = 14.0, stabs = [[157.0, -90.5, 270.0], [109.5, -100.0, 180.0], [157.0, -52.5, 270.0]], holes = [[128.5, -52.5], [147.5, -71.5], [128.5, -90.5], [147.5, -14.5], [109.5, -33.5]], screwR = 1.1, cskR = 2.0, spacerR = 2.15, reliefs = [[126.6, -72.5, 130.4, -70.5], [127.71, -0.4, 130.41, 2.3], [127.71, -2.94, 130.41, -0.24], [127.71, -5.48, 130.41, -2.78], [127.71, -15.64, 130.41, -12.94], [127.71, -18.18, 130.41, -15.48], [127.71, -20.72, 130.41, -18.02], [127.71, -23.26, 130.41, -20.56], [127.71, -25.8, 130.41, -23.1], [112.47, -25.8, 115.17, -23.1], [112.47, -23.26, 115.17, -20.56], [112.47, -20.72, 115.17, -18.02], [112.47, -18.18, 115.17, -15.48], [112.47, -15.64, 115.17, -12.94], [112.47, -5.48, 115.17, -2.78], [112.47, -2.94, 115.17, -0.24], [112.47, -0.4, 115.17, 2.3], [127.125, -32.6, 129.875, -30.4], [127.125, -34.6, 129.875, -32.4], [146.05, 2.03, 147.95, 3.93], [149.05, 2.03, 150.95, 3.93], [136.325, 3.0, 138.075, 4.75], [136.325, 0.25, 138.075, 2.0]];
    var lights = [[128.5, -71.5]], lightR = 0.9;
    var plateT = 1.2, plateBot = 2.6, pcbTop = 1.6, rimW = 1.2, skin = 0.6;
    var S = { dx: 12.0, w: 6.0, h: 12.5, notchW: 1.7, notchD: 1.0, neckH: 2.0, cy: -0.25 };
    var outline = rrect([cx, cy], [pw / 2, ph / 2], pr);

    // stabilizer cutout for a 2u key centred at the origin, in the stab frame: bar on the -y side,
    // wings offset S.cy toward it, notch on the +y end (rotated so -y points at the bar)
    function stabCut() {
        var c = null;
        for (var sgn = -1; sgn <= 1; sgn += 2) {
            var wing = CAG.rectangle({ center: [sgn * S.dx, S.cy], radius: [S.w / 2, S.h / 2] })
                .union(CAG.rectangle({ center: [sgn * S.dx, S.cy + S.h / 2 + S.notchD / 2 - 0.01], radius: [S.notchW / 2, S.notchD / 2] }))
                .union(CAG.rectangle({ corner1: [Math.min(sgn * S.dx, 0), S.cy - S.neckH / 2], corner2: [Math.max(sgn * S.dx, 0), S.cy + S.neckH / 2] }));
            c = c ? c.union(wing) : wing;
        }
        return c;
    }
    var holesCag = null;
    function addHole(h) { holesCag = holesCag ? holesCag.union(h) : h; }
    for (var i = 0; i < sw.length; i++) {
        addHole(CAG.rectangle({ center: sw[i], radius: [swCut / 2, swCut / 2] }));
    }
    // status LED light holes (through), under a keycap-gap crossing
    for (var l = 0; l < lights.length; l++) {
        addHole(CAG.circle({ center: lights[l], radius: lightR, resolution: 24 }));
    }
    for (var s = 0; s < stabs.length; s++) {
        addHole(stabCut().rotateZ(stabs[s][2]).translate([stabs[s][0], stabs[s][1]]));
    }
    // THT pins poking up through the PCB get blind pockets from below (plate top stays closed)
    var pockets = null;
    for (var k = 0; k < reliefs.length; k++) {
        var r = reliefs[k];
        var pk = CAG.rectangle({ corner1: [r[0], r[1]], corner2: [r[2], r[3]] });
        pockets = pockets ? pockets.union(pk) : pk;
    }
    var screwHoles = null;
    for (var j = 0; j < holes.length; j++) {
        var sh = CAG.circle({ center: holes[j], radius: screwR, resolution: 32 });
        screwHoles = screwHoles ? screwHoles.union(sh) : sh;
    }

    // pin pockets are blind from below (plate top stays closed); screw holes go through with a
    // 90 deg countersink on top for the bevel heads
    var plateTop = plateBot + plateT;
    var plate = outline.subtract(holesCag).subtract(screwHoles)
        .extrude({ offset: [0, 0, plateT] }).translate([0, 0, plateBot])
        .subtract(pockets.extrude({ offset: [0, 0, plateT - skin + 0.01] }).translate([0, 0, plateBot - 0.01]));
    for (var c = 0; c < holes.length; c++) {
        plate = plate.subtract(CSG.cylinder({ start: [holes[c][0], holes[c][1], plateTop + 0.2], end: [holes[c][0], holes[c][1], plateTop - (cskR - screwR)],
            radiusStart: cskR + 0.2, radiusEnd: screwR, resolution: 32 }));
    }
    // underneath: a rim along the edge and spacer bosses at the screws, down to the PCB top
    var rim = outline.subtract(rrect([cx, cy], [pw / 2 - rimW, ph / 2 - rimW], Math.max(pr - rimW, 0.3)));
    var bosses = null;
    for (var b = 0; b < holes.length; b++) {
        var bc = CAG.circle({ center: holes[b], radius: spacerR, resolution: 32 });
        bosses = bosses ? bosses.union(bc) : bc;
    }
    var under = rim.union(bosses).subtract(holesCag).subtract(screwHoles).subtract(pockets)
        .extrude({ offset: [0, 0, plateBot - pcbTop + 0.01] }).translate([0, 0, pcbTop]);
    return plate.union(under);
}
